# Generated by Django 4.2.21 on 2025-06-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_questionfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionFile',
        ),
    ]
