# Generated by Django 4.2.21 on 2025-06-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
